# Generated by Django 4.1.4 on 2023-01-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_regions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('info', models.TextField()),
            ],
            options={
                'verbose_name': 'Areas',
                'verbose_name_plural': 'Areases',
            },
        ),
        migrations.AlterModelOptions(
            name='regions',
            options={'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
    ]
